INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (1, 'Tribune Nord', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (2, 'Tribune Sud', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (3, 'VIP Lounge', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (4, 'Buvette Extérieure', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (5, 'Esplanade', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (6, 'Est mobile 1', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (7, 'Est 1', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (8, 'Est mobile 2', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (9, 'Est mobile 3', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (10, 'Est 2', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (11, 'Est mobile 4', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (12, 'Sud 1', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (13, 'Sud 2', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (14, 'Principale Mobile 1', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (15, 'Principale 1', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (16, 'Principale Mobile 2', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (17, 'Principale Mobile 3', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (18, 'Principale 2', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (19, 'Principale Mobile 4', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (20, 'Visiteur', 'STADIUM', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (21, 'Buvette 1', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (22, 'Buvette 2', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (23, 'Buvette 3', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (24, 'Food Genevois', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (25, 'Food Bretzel', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (26, 'Chalet 1', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (27, 'Chalet 2', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (28, 'Chalet 3', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (29, 'Cocktail', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (30, 'Home Corner', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (31, 'Visiteur', 'ARENA', true, 'HOCKEY');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (32, 'Recap Commande Inventaire', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (33, 'START', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (34, 'Inventaire Patinoire & Stade', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (35, 'Inventaire Generale', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (36, 'Réserve Nord', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (37, 'Nord Mobile 1', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (38, 'Nord 1', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (39, 'Nord 2', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (40, 'Nord Mobile 2', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (41, 'Réserve Sud', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (42, 'Rapport tcpos', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (43, 'Inventaire General Patinoire', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (44, '2023', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (45, 'Stock Principal', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (46, 'END', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (47, 'Est Mobile 3', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (48, 'Visiteurs', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (49, 'Principale mobile 1', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (50, 'Principale 1 ', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (51, 'Principale mobile 2', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (52, 'Principale mobile 3', 'Stade', true, 'FOOT');
INSERT INTO `Buvette` (id, name, `locationType`, `isActive`, sport) VALUES (53, 'Principale mobile 4', 'Stade', true, 'FOOT');
